name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string

jobs:
  validate-release:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      changelog: ${{ steps.get-changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Validate Version Format
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format: $VERSION"
            echo "Expected format: v1.0.0"
            exit 1
          fi

      - name: Check if version exists in composer.json
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          COMPOSER_VERSION=$(grep -o '"version": "[^"]*"' composer.json | cut -d'"' -f4 || echo "")
          if [ -n "$COMPOSER_VERSION" ] && [ "v$COMPOSER_VERSION" != "$VERSION" ]; then
            echo "Version mismatch between tag ($VERSION) and composer.json (v$COMPOSER_VERSION)"
            echo "This is acceptable for Magento modules"
          fi

      - name: Extract Changelog
        id: get-changelog
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          VERSION_NUMBER=${VERSION#v}

          # Extract changelog for this version
          if [ -f CHANGELOG.md ]; then
            # Get changelog section for this version
            CHANGELOG=$(awk "/^## \[$VERSION_NUMBER\]/,/^## \[/{if(/^## \[/ && !/^## \[$VERSION_NUMBER\]/) exit; if(!/^## \[$VERSION_NUMBER\]/) print}" CHANGELOG.md)
            if [ -z "$CHANGELOG" ]; then
              echo "No changelog found for version $VERSION_NUMBER"
              CHANGELOG="No changelog available for this release."
            fi
          else
            CHANGELOG="No changelog available for this release."
          fi

          # Use multiline output
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  run-basic-tests:
    name: Run Basic Tests
    needs: validate-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.1", "8.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer

      - name: Validate composer.json
        run: composer validate --no-check-all --no-check-lock

      - name: Check PHP syntax
        run: |
          find src/ lib/ -name "*.php" -exec php -l {} \;
          echo "✅ PHP syntax check passed for PHP ${{ matrix.php-version }}"

  create-release:
    name: Create Release
    needs: [validate-release, run-basic-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Create Release Archive
        run: |
          VERSION="${{ needs.validate-release.outputs.version }}"
          ARCHIVE_NAME="magento2-prometheus-exporter-${VERSION}.zip"

          # Create clean build directory
          mkdir -p build/release

          # Copy necessary files (exclude development files)
          rsync -av \
            --exclude='.git*' \
            --exclude='build/' \
            --exclude='Test/' \
            --exclude='.idea/' \
            --exclude='vendor/' \
            --exclude='composer.lock' \
            --exclude='.github/' \
            --exclude='*.md' \
            . build/release/

          # Ensure required files are included
          cp README.md build/release/ 2>/dev/null || true
          cp CHANGELOG.md build/release/ 2>/dev/null || true
          cp LICENSE build/release/ 2>/dev/null || true

          # Create archive
          cd build/release
          zip -r "../../$ARCHIVE_NAME" . -x "*.git*" "build/*" "Test/*" ".idea/*"
          cd ../..

          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV
          ls -la $ARCHIVE_NAME

      - name: Generate Release Notes
        id: release-notes
        run: |
          VERSION="${{ needs.validate-release.outputs.version }}"
          CHANGELOG="${{ needs.validate-release.outputs.changelog }}"

          cat > release-notes.md << EOF
          # Magento 2 Prometheus Exporter $VERSION

          ## What's Changed

          $CHANGELOG

          ## Installation

          ### Via Composer (Recommended)
          \`\`\`bash
          composer require run_as_root/magento2-prometheus-exporter
          php bin/magento setup:upgrade
          php bin/magento setup:di:compile
          php bin/magento cache:flush
          \`\`\`

          ### Manual Installation
          1. Download the release archive below
          2. Extract to your Magento 2 \`app/code/RunAsRoot/PrometheusExporter\` directory
          3. Run the installation commands above

          ## Compatibility

          - **Magento**: 2.3.x - 2.4.x
          - **PHP**: 7.4 - 8.2

          ## Support

          - 📧 **Email**: info@run-as-root.sh
          - 🐛 **Issues**: [GitHub Issues](https://github.com/run-as-root/magento2-prometheus-exporter/issues)
          - 📖 **Documentation**: [README](https://github.com/run-as-root/magento2-prometheus-exporter#readme)

          **Full Changelog**: https://github.com/run-as-root/magento2-prometheus-exporter/compare/...${VERSION}
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.validate-release.outputs.version }}
          name: ${{ needs.validate-release.outputs.version }}
          body_path: release-notes.md
          files: ${{ env.ARCHIVE_NAME }}
          draft: false
          prerelease: ${{ contains(needs.validate-release.outputs.version, '-') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-packagist:
    name: Update Packagist
    needs: [validate-release, create-release]
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.validate-release.outputs.version, '-') }}
    steps:
      - name: Update Packagist
        run: |
          if [ -n "${{ secrets.PACKAGIST_TOKEN }}" ]; then
            curl -XPOST -H'content-type:application/json' \
              "https://packagist.org/api/update-package?username=run_as_root&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
              -d'{"repository":{"url":"https://packagist.org/packages/run_as_root/magento2-prometheus-exporter"}}'
            echo "✅ Packagist updated successfully"
          else
            echo "⏭️ PACKAGIST_TOKEN not set, skipping Packagist update"
          fi

  release-summary:
    name: Release Summary
    needs: [validate-release, create-release]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Create Release Summary
        run: |
          VERSION="${{ needs.validate-release.outputs.version }}"
          echo "## 🎉 Release $VERSION Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 📦 Release Information" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ needs.create-release.result == 'success' && '✅ Created Successfully' || '❌ Failed' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Release URL**: https://github.com/${{ github.repository }}/releases/tag/$VERSION" >> $GITHUB_STEP_SUMMARY
          echo "- **Packagist**: https://packagist.org/packages/run_as_root/magento2-prometheus-exporter" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.create-release.result }}" == "success" ]]; then
            echo "### 🚀 Next Steps" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Test the release in a development environment" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Update documentation if needed" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Announce release to the community" >> $GITHUB_STEP_SUMMARY
            echo "- [ ] Monitor for any issues" >> $GITHUB_STEP_SUMMARY
          else
            echo "### ❌ Release Failed" >> $GITHUB_STEP_SUMMARY
            echo "Please check the workflow logs for errors and retry the release." >> $GITHUB_STEP_SUMMARY
          fi
